"""add categories accounts and transactions

Revision ID: 1508dc4b1a9b
Revises: 7d0597af3047
Create Date: 2026-08-02 19:16:31.122483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1508dc4b1a9b'
down_revision: Union[str, None] = '7d0597af3047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('checking', 'savings', 'credit', 'investment', 'loan', 'cash', name='account_type'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_id', name='uq_transaction_account_external_id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the fixed system category taxonomy. UUIDs are deterministic
    # (uuid5, not uuid4) and the insert uses ON CONFLICT DO NOTHING keyed
    # on the unique `name` column, so re-running this upgrade (e.g.
    # after a manual partial rollback) does not duplicate rows.
    op.execute(
        """
        INSERT INTO categories (id, name, parent_id, is_system, created_at) VALUES
            ('befcb97b-93d1-5b09-a9b9-56b567bd15a0', 'Income', NULL, true, now()),
            ('3883806c-8ab7-5dfa-a1ee-42f1bed0b6b3', 'Housing', NULL, true, now()),
            ('c8fb4436-76bc-58a0-bf65-70a7ec8b0b09', 'Transportation', NULL, true, now()),
            ('7b24ca2d-92eb-5a40-8fdd-d4ce5a184727', 'Food & Dining', NULL, true, now()),
            ('3c89df6f-4ac0-512a-b727-804acd10b5c3', 'Shopping', NULL, true, now()),
            ('c500c032-8fd3-5fbf-95d3-e6bbae4b4f36', 'Entertainment', NULL, true, now()),
            ('8eeb08ec-c015-5f4d-a1be-7c4203a9f790', 'Health', NULL, true, now()),
            ('2ff067ef-51ea-5144-8acc-164a070d834b', 'Bills & Utilities', NULL, true, now()),
            ('85a6760a-5992-5ca8-b3f0-93eb9a27f87b', 'Savings & Investments', NULL, true, now()),
            ('030bc011-8447-589f-a49b-6dee6619816b', 'Transfer', NULL, true, now()),
            ('56b1fa9f-546a-5c34-94b1-a0fed22db20c', 'Other', NULL, true, now())
        ON CONFLICT (name) DO NOTHING
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    # Postgres native ENUM types are separate objects from the table
    # that used them — DROP TABLE does not drop them. Alembic's
    # autogenerate doesn't add this automatically; found via an actual
    # downgrade-then-upgrade test run in Phase 6, fixed here since
    # upgrade() (already applied) is unaffected.
    op.execute('DROP TYPE IF EXISTS account_type')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
